AreaRingSector.Web/Models/AreaRingSectorViewModel.cs
using System;

namespace AreaRingSector.Web.Models
{
    public class AreaRingSectorViewModel
    {
        public double radius_big { get; set; }
        public double radius_small { get; set; }
        public double angle { get; set; }
        public double result
        {
            get { return Math.Round(new AreaRingSector.Library.AreaRingSector().Calculation(radius_big, radius_small, angle), 2); }
        }
        public string report { get; set; }
    }
}

AreaRingSector.Web/Models/ErrorViewModel.cs
using System;

namespace AreaRingSector.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AreaRingSector.Web/Controllers/AreaRingSectorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using AreaRingSector.Web.Models;

namespace AreaRingSector.Web.Controllers
{
    public class AreaRingSectorController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var view_model = new AreaRingSectorViewModel();
            view_model.radius_big = 3;
            view_model.radius_small = 1;
            view_model.angle = 90;
            return View(view_model);
        }

        [HttpPost]
        public IActionResult Index(IFormCollection form)
        {
            var view_model = new AreaRingSectorViewModel();
            if (!form.TryGetValue("Radius_big", out var R_b) || !form.TryGetValue("Radius_small", out var R_s) || !form.TryGetValue("Angle", out var An))
            {
                R_b = "3";
                R_s = "1";
                An = "90";
                view_model.report = "Не были указаны данные.";
            }
            if (!Double.TryParse(R_b, out var Rb_value) || !Double.TryParse(R_s, out var Rs_value) || !Double.TryParse(An, out var An_value))
            {
                Rb_value = 3;
                Rs_value = 1;
                An_value = 90;
                view_model.report = "Указанное значение не является числовым.";
            }
            view_model.radius_big = Rb_value;
            view_model.radius_small = Rs_value;
            view_model.angle = An_value;
            return View(view_model);
        }
    }
}

AreaRingSector.Web/Controllers/HomeController.cs
using AreaRingSector.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AreaRingSector.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AreaRingSector.Web/Views/AreaRingSector/Index.cshtml
@model AreaRingSector.Web.Models.AreaRingSectorViewModel;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center main-cont">
    <h1 class="display-5" style="padding-bottom: 5%">Площадь сектора кольца</h1>
    <form asp-action="Index" asp-controller="AreaRingSector" method="post" class="form-cont">
        <div class="field-group" style="padding-bottom: 3%; font-size: 22px">
            <label asp-for="radius_big" for="Radius_big" class="label_Rb">Введите больший радиус</label>
            <input asp-for="radius_big" name="Radius_big" class="input_Rb" type="text" value="@Model.radius_big" placeholder="Радиус больше нуля" required>
        </div>
        <div class="field-group" style="padding-bottom: 3%; font-size: 22px">
            <label asp-for="radius_small" for="Radius_small" class="label_Rs">Введите меньший радиус</label>
            <input asp-for="radius_small" name="Radius_small" class="input_Rs" type="text" value="@Model.radius_small" placeholder="Радиус больше нуля" required>
        </div>
        <div class="field-group" style="padding-bottom: 5%; font-size: 22px">
            <label asp-for="angle" for="Angle" class="label_An">Введите угол</label>
            <input asp-for="angle" name="Angle" class="input_An" type="text" value="@Model.angle" placeholder="Угол от 0 до 360" required>
        </div>
        <div class="field-group" style="font-size: 22px;">
            <label asp-for="result" for="Result" class="label_res">Площадь сектора круга</label>
            <input asp-for="result" name="Result" class="input_res" type="text" value="@Model.result" readonly>
        </div>
        <p class="message">@Model.report</p>
        <div class="wrapper">
            <button type="submit" style="border: 2px solid green; border-radius: 4px; font-size: 22px">Рассчитать</button>
        </div>
    </form>
</div>

AreaRingSector.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AreaRingSector.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AreaRingSector.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AreaRingSector.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AreaRingSector" asp-action="Index">Площадь сектора круга</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AreaRingSector.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>